### ISSUE TITLE
ChartRepository#getIndex() now fails on incubator repo

### ISSUE THREAD

**Issue by thrnio** [microbean/microbean-helm#131]
Test case:

~~~java
package example;

import org.microbean.helm.chart.repository.ChartRepository;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

public class HelmChartClassCastExceptionTestCase {
    public static void main(String[] args) throws IOException, URISyntaxException {
        new ChartRepository("incubator",
                            URI.create("https://kubernetes-charts-incubator.storage.googleapis.com/"))
            .getIndex(true);
    }
}
~~~

Running `main()` as of right now gives the following:

~~~
Exception in thread "main" java.lang.ClassCastException: java.util.Date cannot be cast to java.lang.String
	at org.microbean.helm.chart.Metadatas.populateMetadataBuilder(Metadatas.java:98)
	at org.microbean.helm.chart.repository.ChartRepository$Index.loadFrom(ChartRepository.java:1080)
	at org.microbean.helm.chart.repository.ChartRepository$Index.loadFrom(ChartRepository.java:1029)
	at org.microbean.helm.chart.repository.ChartRepository.getIndex(ChartRepository.java:495)
	at com.puppet.pipelines.helm.HelmChartClassCastExceptionTestCase.main(HelmChartClassCastExceptionTestCase.java:13)

Process finished with exit code 1
~~~

This changed when this PR got merged to kubernetes/charts: https://github.com/kubernetes/charts/pull/4579

The key change is the addition of an `appVersion` which is a date. This causes SnakeYAML to parse it into a `java.util.Date`, which means this cast fails: https://github.com/microbean/microbean-helm/blob/21fb09e15b2a8666810e2601a70185a19fed5813/src/main/java/org/microbean/helm/chart/Metadatas.java#L98

Since the error propagates all the way up the call stack, there's not even a straightforward way to work around it. This issue isn't limited to incubator; if that chart or any other chart with a field that looks like a date makes it into stable or any other repository, the same issue will occur.

**Comment by ljnelson** [comment]
Crappo; yes; need to force SnakeYAML somehow to parse pretty much every scalar as a `String`.

A quick but unsatisfactory fix IMHO is to let SnakeYAML parse the field however it likes, and then, if it's a `Date` or some other time construct, use the appropriate formatter to serialize it back into a canonical string before calling `setAppVersion` on the builder.  But that's gross.

Going to dig deeper into SnakeYAML and see if there's some _easy_ universal way to say: hands off conversion, Jack.

**Comment by ljnelson** [comment]
_Ugh_.  This is really irritating.

The PR you reference in the incubator repo "solves" the issue by quoting the appVersion value.  This relies on the parser to use this as an indication that the value is a string.  SnakeYAML appears? maybe? not to be honoring this effective type conversion.

The SnakeYAML parser has a lot of implicit type resolution.  The one that is relevant is here: https://bitbucket.org/asomov/snakeyaml/src/599d02a450e78d2a2daf9ee3ba2863c20532e45d/src/main/java/org/yaml/snakeyaml/resolver/Resolver.java?at=default&fileviewer=file-view-default#Resolver.java-45:46

So clearly this pattern is the one that is matching.

Note that the pattern matches when the first character is a digit (among other things).  That means by the time this `Pattern` is matched, the quote has been discarded somehow.  This may be a severe bug in SnakeYAML, or something that I simply haven't configured properly when loading YAML.  Still investigating.

**Comment by ljnelson** [comment]
Naïvely, it looks like the lexing gets rid of the quotes: https://bitbucket.org/asomov/snakeyaml/src/599d02a450e78d2a2daf9ee3ba2863c20532e45d/src/main/java/org/yaml/snakeyaml/scanner/ScannerImpl.java?at=default&fileviewer=file-view-default#ScannerImpl.java-1848

I think this means that any scalar value, quoted or not, will still be run through the implicit type resolution stuff.  So even though the intent is to force string coercion, the value that will be inspected will simply be `2018-01-01` (or whatever it is), not `"2018-01-01"`.

**Comment by thrnio** [comment]
The YAML spec has very few requirements around how to process values. All quotes are required to do is ensure that the entire content is treated as a single value (okay, it's a bit more complicated than that, but close enough). Parsers are pretty much allowed to interpret anything without an explicit type declaration however they want <_<

**Comment by ljnelson** [comment]
See also: https://stackoverflow.com/questions/49889416/in-yaml-must-a-quoted-scalar-be-interpreted-by-a-parser-as-a-string

**Comment by ljnelson** [comment]
Right, in which case a good portion of Helm's serialization is strictly speaking non-deterministic.

For this issue, I think I will band-aid it since I can't anticipate which of several string properties might actually be dates, or vice versa.

**Comment by thrnio** [comment]
And this is why building a product and spec around YAML is a bad idea :)

**Comment by seglo** [comment]
I'm getting a similar issue when attempting to load the stable chart repo: https://kubernetes-charts.storage.googleapis.com/index.yaml

I'm using version `2.8.2.1.1.0`

Stacktrace:

```
java.lang.String cannot be cast to java.util.Map
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.microbean.helm.chart.repository.ChartRepository$Index.loadFrom(ChartRepository.java:1560)
	at org.microbean.helm.chart.repository.ChartRepository$Index.loadFrom(ChartRepository.java:1528)
	at org.microbean.helm.chart.repository.ChartRepository.getIndex(ChartRepository.java:884)
	at org.microbean.helm.chart.repository.ChartRepository.getIndex(ChartRepository.java:787)
```

**Comment by ljnelson** [comment]
That's odd.  I'll open a new issue starting with your comment.

**Comment by ljnelson** [comment]
See #172.

**Comment by seglo** [comment]
Thanks.  I should have created the issue in the first place.
