### ISSUE TITLE
Should load YAML using SnakeYAML's SafeConstructor

### ISSUE THREAD

**Issue by thrnio** [microbean/microbean-helm#132]
Since (AFAICT) none of the YAML has any reason to be converted into non-core java types, as per the SnakeYAML docs, the library should use `SafeConstructor` for deserialization. For example, this

https://github.com/microbean/microbean-helm/blob/21fb09e15b2a8666810e2601a70185a19fed5813/src/main/java/org/microbean/helm/chart/repository/ChartRepository.java#L1029

should be

~~~java
 final Map<?, ?> yamlMap = new Yaml(new SafeConstructor()).loadAs(stream, Map.class); 
~~~

**Comment by ljnelson** [comment]
Oh, that's interesting; thanks for the catch.  I'm no SnakeYAML expert so this is helpful.

**Comment by ljnelson** [comment]
Just informational: Investigating further, it appears that there are some cases where it's not just non-core Java types.  `requirements.yaml` processing needs to create POJOs of other kinds during deserialization.

**Comment by ljnelson** [comment]
This may turn out to be "works as it does".  Attempts to use `SafeConstructor` in other places that load YAML as a `Map` of `Map`s don't work because a new `HashMap` has to be constructed.  Still investigating.  I'll add `SafeConstructor` anywhere I can, but it's looking more and more like that's not going to be very many places.

**Comment by ljnelson** [comment]
Even weirder.  I use this construct:

    final Map<?, ?> crap = new Yaml().loadAs(someStream, Map.class)

If I change that to:

    final Map<?, ?> crap = new Yaml(new SafeConstructor()).loadAs(someStream, Map.class)

…it fails.  If I instead do:

    final Map<?, ?> crap = new Yaml(new SafeConstructor()).load(someStream)

…it works.  IMHO these should be identical.

The second construct seems to be safer so I'll experiment with using that in as many places as I can.
