### ISSUE TITLE
chart install failed when it includes requirements.yaml file with none numeric value

### ISSUE THREAD

**Issue by eyalholz** [microbean/microbean-helm#133]
Failed with “Unexpected character 'ILLEGAL(~)' at position '0', expecting '[DIGIT]'” message on try to install chart that contains requirements.yaml file with version value that is not numeric (e.g with ~ as prefix).
Helm allows to use version ranges instead of pinning to an exact version. 
Attached link describes it: https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/requirements.md

**Comment by ljnelson** [comment]
Odd; I thought perhaps I was casting values, but I'm getting them out of the YAML document as `String`s.  So the problem is not with `StreamOrientedChartLoader`.  Hmm.  Investigating further.

**Comment by ljnelson** [comment]
I believe the problem is here: https://github.com/microbean/microbean-helm/blob/v2.8.2.1.0.3/src/main/java/org/microbean/helm/chart/Requirements.java#L1024

The code at that location does not look correct for dealing with semantic versions.  Still investigating.

**Comment by ljnelson** [comment]
Yep; got it 100% backwards 🙄.  Working on a fix now.
