### ISSUE TITLE
fail to import through pom.xml

### ISSUE THREAD

**Issue by jiaj12** [microbean/microbean-helm#135]
hi there I tried to include your microbean-helm project as a dependency to my work.
but it gives me an error
Could not find artifact io.netty:netty-tcnative-boringssl-static:jar:${os.detected.classifier}:2.0.6.Final in central (https://repo.maven.apache.org/maven2) 
I tried to google it, but it seems no solution for the eclipse version which i'm using version:oxygeon

Have you met this problem?
thx

**Comment by ljnelson** [comment]
You will need the `os-maven-plugin`: 

    <build>
      <extensions>
        <extension>
            <groupId>kr.motd.maven</groupId>
            <artifactId>os-maven-plugin</artifactId>
            <version>1.5.0.Final</version>
        </extension>
      </extensions>
      
    </build>

**Comment by jiaj12** [comment]
thanks a lot! problem solved

**Comment by shadjiiski** [comment]
Oh man, I found this way after I deduced the solution myself :D I have created a pull request to include this info in the README if you think it is a good idea (#176)
