### ISSUE TITLE
Need sample code for simulating request "helm status --output yaml mychart"

### ISSUE THREAD

**Issue by bestro** [microbean/microbean-helm#136]
Hi,

Is there a possibility to simulate this command "helm status **--output yaml** mychart"  using the API. 

I cannot find any option to send the **"--output yaml"** parameter to the **GetReleaseStatusRequest** class.

**Comment by ljnelson** [comment]
Hello; thanks for using microBean Helm.  microBean Helm is a library providing access to the building blocks of whatever kind of Helm client you want to make.  As such, it is not a command line tool, so there are no command line options.

It sounds like ultimately you are trying to receive the information that Tiller has about the status of a Helm release, and then print that information to standard out, formatted as YAML.

That means you'll want to work backwards from here: https://microbean.github.io/microbean-helm/apidocs/hapi/services/tiller/Tiller.GetReleaseStatusResponseOrBuilder.html

To get one of these, you'll want to issue a status request: https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/ReleaseManager.html#getStatus-hapi.services.tiller.Tiller.GetReleaseStatusRequest-

You can see that this is how `helm` works: https://github.com/kubernetes/helm/blob/v2.8.2/cmd/helm/status.go#L114-L141

Hope that helps you out.
