### ISSUE TITLE
We need an ability to coonect to Helm Repository via Proxy

### ISSUE THREAD

**Issue by fidget83** [microbean/microbean-helm#145]
We need an ability to coonect to Helm Repository via Proxy, if node, where client is running, has no access to Internet

**Comment by ljnelson** [comment]
Thanks for using microBean Helm.  I see your pull request; thanks for that.  Before I merge it and cut a new release, you can of course do what you need by subclassing.

**Comment by fidget83** [comment]
Hello,
could you please tell me, when are you going to release a new version with this change?

**Comment by ljnelson** [comment]
Hello; I edited #146 lightly and merged it just now.  All tests pass.  Thanks for your contribution.

**Comment by fidget83** [comment]
Thanks a lot!
