### ISSUE TITLE
os.detected.classifier from transient dependancy not set and gioving build errors

### ISSUE THREAD

**Issue by OmkarBi** [microbean/microbean-helm#154]
Is there a preconfiguration needed for {os.detected.classifier} to be populated?

`Errors occurred while build effective model from /.gradle/caches/modules-2/files-2.1/org.microbean/microbean-helm/2.8.2.1.0.4/44fb98754ff742b4a237718238bd9cced7906ffd/microbean-helm-2.8.2.1.0.4.pom:
    'build.resources.resource.directory' is missing. in org.microbean:microbean-helm:2.8.2.1.0.4
Errors occurred while build effective model from /.gradle/caches/modules-2/files-2.1/org.microbean/microbean-development-annotations/0.1.3/abaddafbff41cfff5f9332014aa30a7506498e6d/microbean-development-annotations-0.1.3.pom:
    'build.resources.resource.directory' is missing. in org.microbean:microbean-development-annotations:0.1.3
Errors occurred while build effective model from /.gradle/caches/modules-2/files-2.1/org.microbean/microbean-kubernetes/0.1.1/7fdace2d7ffa0c5e56e9f588ecc632a6333fe655/microbean-kubernetes-0.1.1.pom:
    'build.resources.resource.directory' is missing. in org.microbean:microbean-kubernetes:0.1.1
<ij_msg_gr>Project resolve errors<ij_msg_gr><ij_nav>/build.gradle<ij_nav><i><b>root project 't-admin': Unable to resolve additional project configuration.</b><eol>Details: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':compileClasspath'.<eol>Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find netty-tcnative-boringssl-static-${os.detected.classifier}.jar (io.netty:netty-tcnative-boringssl-static:2.0.6.Final).<eol>Searched in the following locations:<eol>    https://binrepo.target.com/artifactory/tgt-repo/io/netty/netty-tcnative-boringssl-static/2.0.6.Final/netty-tcnative-boringssl-static-2.0.6.Final-${os.detected.classifier}.jar</i>
<ij_msg_gr>Project resolve errors<ij_msg_gr><ij_nav>/t-admin/build.gradle<ij_nav><i><b>root project 't-admin': Unable to resolve additional project configuration.</b><eol>Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':compileClasspath'.<eol>Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find netty-tcnative-boringssl-static-${os.detected.classifier}.jar (io.netty:netty-tcnative-boringssl-static:2.0.6.Final).<eol>Searched in the following locations:<eol>    .../2.0.6.Final/netty-tcnative-boringssl-static-2.0.6.Final-${os.detected.classifier}.jar</i>
`

**Comment by OmkarBi** [comment]
duplicate

**Comment by shadjiiski** [comment]
solution is in #135
