### ISSUE TITLE
Client cannot connect to private Helm repositories

### ISSUE THREAD

**Issue by fidget83** [microbean/microbean-helm#160]
In our company we use Basic Auth to restrict access to Helm repository. In this case client cannot connect to repo. I suggest to add such an ability.

**Comment by ljnelson** [comment]
Please see https://docs.oracle.com/javase/8/docs/api/java/net/Authenticator.html and see if that would handle your needs.

**Comment by fidget83** [comment]
Thnak you very much! It was really nice and helpful :)
Example of usage:
https://www.blackbaud.com/files/support/infinitydevguidemobile/Advanced/Subsystems/inwebapi-developer-help/Content/Java/coJavaBasicAuthentication.htm
