### ISSUE TITLE
empty HELM_HOME directory

### ISSUE THREAD

**Issue by avichap** [microbean/microbean-helm#162]
Hi,

Currently the `ChartRepository` class implementation  assumes that the helm home directory is pre created  and initialized  with helm client side directory structure using `helm init`.

it looks that if the helm home is empty the `ChartRepository` code should have created the helm client side initial structure.

Thanks,
Avi,

**Comment by ljnelson** [comment]
Also need to look at `ChartRepositoryRepository` here as well.

**Comment by ljnelson** [comment]
Fixed.  I deployed a snapshot [here](https://oss.sonatype.org/content/repositories/snapshots/org/microbean/microbean-helm/2.8.2.1.1.0-SNAPSHOT/).  Would you mind testing it out?  You'll see a new `reifyHelmHomeIfNecessary` `boolean` parameter for several related methods; setting this to `true` should cause auto-reification of the `HELM_HOME` directory structure when needed.

**Comment by avichap** [comment]
Hi ,

We have tested it and it worked for us. Thanks

Avi,
