### ISSUE TITLE
More YAML problems when loading stable index

### ISSUE THREAD

**Issue by ljnelson** [microbean/microbean-helm#172]
User @seglo reports:

> I'm getting a similar issue when attempting to load the stable chart repo: https://kubernetes-charts.storage.googleapis.com/index.yaml
>
> I'm using version `2.8.2.1.1.0`
>
> Stacktrace:
>
> ```
> java.lang.String cannot be cast to java.util.Map
> java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
>	at org.microbean.helm.chart.repository.ChartRepository$Index.loadFrom(ChartRepository.java:1560)
>	at org.microbean.helm.chart.repository.ChartRepository$Index.loadFrom(ChartRepository.java:1528)
>	at org.microbean.helm.chart.repository.ChartRepository.getIndex(ChartRepository.java:884)
>	at org.microbean.helm.chart.repository.ChartRepository.getIndex(ChartRepository.java:787)
> ```

**Comment by ljnelson** [comment]
I cannot reproduce this.  I downloaded the `index.yaml` by hand, and created a test case that attempts to load it.  The load works fine.  I'll push a branch with this test case in it; maybe you can discover a discrepancy between your use case and my test case?

**Comment by ljnelson** [comment]
Related PR: https://github.com/microbean/microbean-helm/pull/173.  @seglo, maybe take a look and see if I've missed something?

**Comment by seglo** [comment]
That's odd.  This is my calling code (using Scala).

```
val repository = new ChartRepository("kubeapps-stable", URI.create("https://kubernetes-charts.storage.googleapis.com/index.yaml"))
```

**Comment by seglo** [comment]
I assumed the URI parameter was so that the index yaml could be fetched.  Your use case pre-fetches it.  Is that what I should be doing too?

**Comment by ljnelson** [comment]
OK; that by itself won't cause a download.  Do you then do something like `repository.getIndex()`?  Ultimately this will end up calling `repository.loadIndex()`.  Maybe you have something gross in your helm home cache?

**Comment by ljnelson** [comment]
> I assumed the URI parameter was so that the index yaml could be fetched. Your use case pre-fetches it. Is that what I should be doing too?

No, you should be fine.  The full Javadocs of the constructor you're using are here:
https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/chart/repository/ChartRepository.html#ChartRepository-java.lang.String-java.net.URI-

(The reason I preload in my test case is so that I am loading from a known `index.yaml`.  One of the many, many, many, many, many design flaws in Helm's chart repository system is that the `index.yaml` itself is just…whatever it is at whatever point you look at it.)

So if you use the constructor that just takes a name and a `URI`, you are saying effectively: "Please use the normal `helm` home caching structure for when you download the point-in-time copy of `index.yaml`, and then read it from that cached copy."  This is exactly how the `helm` command line works.

(In my test case, I am effectively saying: "Please don't use the `helm` home caching structure, and, instead, read from this explicitly cached copy that I've just slid in under the covers into the right place.")

**Comment by seglo** [comment]
Ah, yes I had a garbage file in my cache at `~/.helm/repository/cache/kubeapps-stable-index.yaml` I think from an earlier attempt at trying to figure out the index YAML URL.  It was an HTML blob.

**Comment by ljnelson** [comment]
Whew!  Regrettably, there's not an easy way to get SnakeYAML to do much other than puke out `ClassCastException`s when there's garbage input.  It would be nice to be able to say, "Er, this doesn't look like a chart index."

With your permission, I'll commit the pull request just since it references another snapshot of the master index (seems useful) and will close this issue.

**Comment by seglo** [comment]
Sounds good.  Thanks for the super prompt replies too!

**Comment by ljnelson** [comment]
Closed with https://github.com/microbean/microbean-helm/commit/b3147b4dc705a27641e40e2c29cc6f7081012b69 (#173).
