### ISSUE TITLE
Document the usage of URLChartLoader

### ISSUE THREAD

**Issue by iming0319** [microbean/microbean-helm#174]
I just follow the example at https://microbean.github.io/microbean-helm/examples.html
And I got connection time out in `chart = chartLoader.load(url);`
```
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
```

I can get the file in the same pc without any problem.
Do I have to do anything before loading the chart?

**Comment by ljnelson** [comment]
No, that should work.  Usually a connection timeout is not something I have control over.  Can you provide more details?

**Comment by ljnelson** [comment]
Closing; please feel free to open a new issue if you find any problems with microBean Helm.
