### ISSUE TITLE
How to handle the protected HelmCharts (.tgz)

### ISSUE THREAD

**Issue by vinapp** [microbean/microbean-helm#185]
Our helm repo is protected by Basic authentication. Would like to know how do we load the charts (using URLChartLoader) that are protected by Basic auth.

**Comment by fidget83** [comment]
E.g.
/**
	 * Need to make a basic auth in Helm Repository
	 * See https://docs.oracle.com/javase/7/docs/api/java/net/Authenticator.html#getPasswordAuthentication()
	 */
	static class BasicAuthenticator extends Authenticator {
		private String username;
		private String password;

		private BasicAuthenticator(String username, String password) {
			this.username = username;
			this.password = password;
		}

		@Override
		public PasswordAuthentication getPasswordAuthentication() {
			log.debug("Authenticating in Helm Repository using provided credentials");
			return new PasswordAuthentication(username, password.toCharArray());
		}
	}

And then just call 
Authenticator.setDefault(new BasicAuthenticator(HELM_REPOSITORY_USERNAME, HELM_REPOSITORY_PASSWORD));

when getting chart repository.

**Comment by vinapp** [comment]
@fidget83  Thanks, It worked. One final question (not relevant to the above one). Is there an equivalent API for "helm search" command

**Comment by ljnelson** [comment]
No, there is not.  For interactive applications, you are best off using the `helm` command line API.  The use cases for microBean Helm start when you already know what chart you need.

**Comment by NMSVishal** [comment]
Above basic authentication is not working correctly ,it failed with "java.net.ProtocolException: Server redirected too many  times (20) exception". Event though I have set up Cookie Manager before setting up basic authentication same exception is coming
