### ISSUE TITLE
Upgrade or install release

### ISSUE THREAD

**Issue by gavinfish** [microbean/microbean-helm#188]
How to use this sdk to execute command like `helm upgrade <release name> --install` to upgrade a release if it exists, otherwise just install it.

**Comment by ljnelson** [comment]
You'll have to do this yourself.  I'd imagine you would start with this: https://microbean.github.io/microbean-helm/apidocs/hapi/services/tiller/Tiller.GetReleaseStatusRequest.Builder.html

...and then based on the return value from https://microbean.github.io/microbean-helm/apidocs/hapi/services/tiller/ReleaseServiceGrpc.ReleaseServiceBlockingStub.html#getReleaseStatus-hapi.services.tiller.Tiller.GetReleaseStatusRequest-

…you can choose to install or not.

My recollection is this is how `helm` does it internally.  Of course, this may still fail, as someone else may conceivably install the chart in between your status request and installation request.
