### ISSUE TITLE
Namespace field in InstallReleaseRequest type object  should be optional as helm allow installing charts without namespace

### ISSUE THREAD

**Issue by Netaji-Surve** [microbean/microbean-helm#190]
Explanation:
I am trying to install a chart which has a namespace specified within its template file. In this case if I try to give  namespace in InstallReleaseRequest object also then helm  is throwing error of duplicate namespace.

Helm command allow us to install charts without having namespace parameter, in that case it will install helm release in "default" namespace.

I think microbean should also have similar behavior. We should have namespace field as optional in InstallReleaseRequest object.

Code Reference:
Tiller.class (line 5804)

 public Tiller.InstallReleaseRequest.Builder setNamespace(String value) {
                if (value == null) {
                    throw new NullPointerException();
                } else {
                    this.namespace_ = value;
                    this.onChanged();
                    return this;
                }
    }

**Comment by ljnelson** [comment]
Hello; thanks for using microBean Helm.  I don't have control over that class; it is generated.

**Comment by Netaji-Surve** [comment]
HI,
Can you please explain how it is generated and how can we handle this null condition?

**Comment by ljnelson** [comment]
The API classes that interact with Tiller are generated from Helm's protocol buffers source files: https://github.com/helm/helm/tree/master/_proto

The way they are generated uses `protoc` and the gRPC Java plugin: https://github.com/grpc/grpc-java#grpc-java---an-rpc-library-and-framework

In terms of which fields and methods and whatnot may be `null` or not within them, I'm honestly not sure off the top of my head.
