### ISSUE TITLE
UNAVAILABLE: Keepalive failed

### ISSUE THREAD

**Issue by jasonrita** [microbean/microbean-helm#192]
Always report errors when installing tgz apps: io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone

**Comment by ljnelson** [comment]
Hello; thanks for using microBean Helm.  It is difficult to understand what you're reporting, but you may wish to build the `ManagedChannel` that your `Tiller` instance uses with appropriate timeouts set.  Please see https://grpc.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#keepAliveTime-long-java.util.concurrent.TimeUnit- for possible ways forward.
