### ISSUE TITLE
equivalent of 'helm template'

### ISSUE THREAD

**Issue by rhubarb** [microbean/microbean-helm#194]
Is there an equivalent for the 'helm template' command that simply resolves the chart on the client side without contacting Tiller?
I would like to use this library from a java-groovy build process to resolve charts into pure yaml files during build - with no kubernetes cluster involved.

**Comment by ljnelson** [comment]
Hello; no, there is not; I'd have to rewrite Go templating in Java.  In general, pure client-side operations are by design not supported in microbean-helm.
