### ISSUE TITLE
ReleaseManager.list() hang forever

### ISSUE THREAD

**Issue by gavinfish** [microbean/microbean-helm#196]
Communicating with Tiller will hang in some environment, any suggestions for troubleshooting here?

**Comment by ljnelson** [comment]
There's not much I can do, I don't think.  I'm going to guess that the connectivity issues are going to be some combination of gRPC's internals and/or the fabric8 Kubernetes client.  Please let me know if you discover otherwise.

**Comment by ljnelson** [comment]
Closing as this is not an issue related to microBean Helm.
