### ISSUE TITLE
Configure microbean to use Tiller on another machine

### ISSUE THREAD

**Issue by michaelabdo** [microbean/microbean-helm#197]
I was having a look at the project and I was wondering if it was possible to configure the settings to connect to helm & tiller on a different machine.
Both machines are in offline environments but are able to communicate to one another.
Tiller is installed in the cluster on the master. I am working in eclipse on a dev machine.
So for the helm commands pass them through to the master and to receive tiller information from the master.
Thanks

**Comment by ljnelson** [comment]
Hello; thanks for using microBean Helm.  i assume you answered your own question!

**Comment by michaelabdo** [comment]
Hello,

Sorry to open this again. 
So the reason I closed this was because I managed to connect to the Kubernetes machine, and I thought it would be smooth sailing from there, alas it is never as simple as that.
I am not sure if this will count as the same issue, but I believe RBAC on my K8s cluster is preventing me from receiving information within namespaces. I am capable of retrieving GitCommit from the cluster along with other basic version functions, but as soon as I try list pods (even with/without Helm), I receive an error like:

replicationcontrollers is forbidden: User "system:anonymous" cannot watch replication controllers in the namespace "default"

I'm confused as to why it considers my dev machine "system:anonymous" although i include a username and password using functions withUsername/Password(uname/pass)  in the ConfigBuilder().
I know this isn't really microbean, as its more on the "io.fabric8.kubernetes" side, but I was wondering if you recommend a particular way to go about this for microbean considering Tiller is involved?
If this is the case can you recommend any particular remedy from experience?

Thanks

**Comment by michaelabdo** [comment]
I just wanted to leave a comment saying I will be uploading my project on my GitHub in the coming month, so if anyone would like to see how this works you will find the code on my site!
