### ISSUE TITLE
ListReleasesResponseOrBuilder - List all function

### ISSUE THREAD

**Issue by michaelabdo** [microbean/microbean-helm#198]
Hello,

Is there a current or planned enhancement to Tiller.ListReleasesResponseOrBuilder, to be capable of listing charts with all statuses?
I am currently capable of listing all deployed charts, however, I want to list deleted charts too (_**helm list --all**_).
This is my current code, I am guessing if there is any method it would be in the ListReleasesResponse class, but im unable to find anything.

															

			
		final ListReleasesRequest.Builder requestBuilder = ListReleasesRequest.newBuilder();	
								
		assert requestBuilder != null;	
		
		final Iterator<ListReleasesResponse> releaseFuture = releaseManager.list(requestBuilder.build());				
		assert releaseFuture != null;																			

		
		
		while (releaseFuture.hasNext()) {															
			ListReleasesResponse releases = releaseFuture.next();														
			logger.info("Releases Count: " + releases.getReleasesCount());												
			logger.info("Total Count: " + releases.getTotal());
			
			List<Release> releaseList = releases.getReleasesList();														
					
			for(Release release : releaseList) {
				logger.info("***");																
				logger.info("Rel_Name:	{}", release.getName());												
				logger.info("Chart_name:	{}", release.getChart().getMetadata().getName());
				logger.info("Revision_Ver:	{}", release.getVersion());
				logger.info("Chart_Ver:	{}", release.getChart().getMetadata().getVersion());
				logger.info("Namespace:	{}", release.getNamespace());
				logger.info("Status:	{}", release.getInfo().getStatus().getCode().toString());
				logger.info("***");
			}
		}

Thanks!

**Comment by ljnelson** [comment]
This should get you started: https://microbean.github.io/microbean-helm/apidocs/hapi/services/tiller/Tiller.ListReleasesRequest.Builder.html#addAllStatusCodes-java.lang.Iterable-

A reminder that anything in the `hapi.` package hierarchy is generated.

**Comment by michaelabdo** [comment]
@ljnelson Thanks so much, mate!

For those wondering i changed the following line:
`	final Iterator<ListReleasesResponse> releaseFuture = releaseManager.list(requestBuilder.build());				`

to:
`final Iterator<ListReleasesResponse> releaseFuture = releaseManager.list(requestBuilder.addStatusCodesValue(2).build());`

This displays the deleted Charts
