### ISSUE TITLE
Incorrect time set to  tar header in TapeArchiveChartWriter

### ISSUE THREAD

**Issue by frantic777** [microbean/microbean-helm#200]
Hi there,

Looks like there is a small issue with TapeArchiveChartWriter.writeEntry(...). On line 137 it sets time to System.currentTimeMillis() which is incorrect since it expects Unix time which is epoch second. That could be fixed by division by 1000. I.e. the parameter should be System.currentTimeMillis()/1000.

Cheers,
Alex

**Comment by ljnelson** [comment]
Thanks! Fixing as we speak.
