### ISSUE TITLE
Connection timeout at releaseManager.list()

### ISSUE THREAD

**Issue by tht-activeviam** [microbean/microbean-helm#203]
There is no method to increase the timeout in `hapi.services.tiller.Tiller.ListReleasesRequest.Builder`.
With slow connection, I am getting connection timeout error from `releaseManager.list(listRequestBuilder.build())`

Both of these have `setTimeout()` method:
- hapi.services.tiller.Tiller.UninstallReleaseRequest.Builder
- hapi.services.tiller.Tiller.InstallReleaseRequest.Builder

**Comment by ljnelson** [comment]
Sadly, these are generated APIs.  You can read the original protobuf files here: https://github.com/helm/helm/blob/eecf22f77df5f65c823aacd2dbd30ae6c65f186e/_proto/hapi/services/tiller.proto#L88-L118.

[microBean™ Helm's Javadocs](https://microbean.github.io/microbean-helm/apidocs/index.html) indicate that classes in the `hapi` package hierarchy are generated and I have no control over them.  This would be an issue to take up with the Helm team.

Thank you for your interest in and usage of microBean™ Helm!
