### ISSUE TITLE
releaseManager.uninstall() can't delete deployment without throwing any exception .my k8s version is 1.17.2,mecrobean-helm version is 2.7.0

### ISSUE THREAD

**Issue by zhupeixiang1234** [microbean/microbean-helm#207]
but this method can delete StatefulSet .why?

**Comment by ljnelson** [comment]
This may have to do with the fact that in Helm 2.8.x and lower which were targeted at older versions of Kubernetes the `Deployment` construct was still in alpha or beta (I forget which).

**Comment by zhupeixiang1234** [comment]
> This may have to do with the fact that in Helm 2.8.x and lower which were targeted at older versions of Kubernetes the`Deployment`construct was still in alpha or beta (I forget which).

so,if i want to solve the problem ,i can update  the version of micro-helm .but,which version i can choose . the apiversion of deployment is apps/v1 .

**Comment by zhupeixiang1234** [comment]
my helm version is 3.1 now,can i use the version 2.12 of microbean-helm?

**Comment by ljnelson** [comment]
There's no such version; the current releases are here: https://github.com/microbean/microbean-helm/releases

**Comment by ljnelson** [comment]
Please also note that in the meantime Helm itself has moved to version 3, and no longer has a Tiller component, so the gRPC/Protocol Buffers part of this project is mostly irrelevant for Helm 3.  When I get time, I'll be porting Helm 3 to Java by hand.

**Comment by zhupeixiang1234** [comment]
thank you very much,I have resolved the problem,I update helm and tiller to 2.16.3 and use microbean-helm 2.12.3.0.0.1-SNAPSHOT ,now,the deployment can be deleted.
