### ISSUE TITLE
Error parsing image.tag from values.yaml,"1.0" became "1"

### ISSUE THREAD

**Issue by daiqingliang** [microbean/microbean-helm#209]
Hi,Laird!
I got a problem when use microBean Helm to install a chart.
The image sets from ```values.yaml ```:
```
...
image: 
    repository: daiqingliang/springboot-env
    tag: 1.0
    pullPolicay: IfNotPresent
...
```
When I use ```TarArchiveChartLoader ``` install a ```tgz``` type chart,  
 I found the pod fail to create,so I check the pod,and found image became this:
```
...
containers:
    - name: springboot-env
      image: 'daiqingliang/springboot-env:1'
...
```
And you told me that YAML does not hava types,So a text value of "1.0" may be interpreted by a YAML parser as 1(int).
So there show be a bug here.

**Comment by ljnelson** [comment]
Could you kindly try doing:
```
    tag: "1.0"
```
…?  The SnakeYAML parser used by microBean™ Helm may force this to a `String`.

**Comment by daiqingliang** [comment]
> Could you kindly try doing:
> 
> ```
>     tag: "1.0"
> ```
> 
> …? The SnakeYAML parser used by microBean™ Helm may force this to a `String`.  

Yap, ``` tag: "1.0" ``` work fine!
