### ISSUE TITLE
ReleaseManager.list not return all releases

### ISSUE THREAD

**Issue by baikai** [microbean/microbean-helm#212]
API releaseManager.list not return all releases, this api seems just return releases with "deployed" status. For example, there have 4 release like below:
NAME            REVISION        UPDATED                         STATUS          CHART         APP VERSION     NAMESPACE
release01       1               Thu May 28 08:41:39 2020        DEPLOYED        chart01         0.8.0           default
release02       1               Thu Mar 26 13:38:42 2020        DEPLOYED        chart01         0.0.1           kube-system
release03       1               Thu Mar 26 10:12:45 2020        FAILED          chart02         0.0.1           kube-system
release04       1               Fri Oct 11 09:19:22 2019        DEPLOYED        chart02         1.0             default
API releaseManager.list return release01, release 02 and release04 to caller, but the release03 be ignored.

**Comment by ljnelson** [comment]
As you can see in the code below:

https://github.com/microbean/microbean-helm/blob/a42ace8ba3b9e1a5efa5ccc7b18e9f43ade9c109/src/main/java/org/microbean/helm/ReleaseManager.java#L405-L412

…all `ReleaseManager` does is pass the request to Tiller.  So there's nothing that microBean Helm™ can do here.  Maybe your request was created in such a way that it deliberately omits `release03`?

**Comment by baikai** [comment]
@ljnelson thx, I read the code segment above, as you said that releaseManager just pass the request to tiller directly. 
But when I debug the releaseManager.list and print the response, I found response not contains release03. 
My question is whether the switch or filter included in ListReleasesRequest? I checked ListReleasesRequest class definition but nothing found.

**Comment by ljnelson** [comment]
As noted in the microBean Helm™ documentation, these classes are generated from protobuf files maintained by Helm itself.  So I have no control over them or how they're used.

It looks like you can add a filter to your request by making use of this class method: https://microbean.github.io/microbean-helm/apidocs/hapi/services/tiller/Tiller.ListReleasesRequest.Builder.html#setFilter-java.lang.String-

**Comment by baikai** [comment]
@ljnelson thx, do you have sample code about how to use request filter? API doc told me to set filter to "4",  but it's not works. 
Another question is release contains several column, like name, status, chart, updated..., which column will be affected by the filter ? thx

**Comment by baikai** [comment]
@ljnelson after read tiller api doc and testing, I found the release list result can be changed by _setStatusCode_.
For example, when I construct list release request by code _ListReleasesRequest.newBuilder().addStatusCodesValue(4).build()_(different code number means different release status), the failed release will be returned to caller. No need to add any extra filter in request body.
So, it's not problem and I will close it, thx.
