### ISSUE TITLE
Cannot resolve io.netty:netty-tcnative-boringssl-static:2.0.7.Final

### ISSUE THREAD

**Issue by nuclearwu** [microbean/microbean-helm#214]
Cannot resolve io.netty:netty-tcnative-boringssl-static:2.0.7.Final

**Comment by nuclearwu** [comment]
![image](https://user-images.githubusercontent.com/37976659/156727407-7be56d4f-f2e8-4687-8e0a-80dbe5d77749.png)

**Comment by ljnelson** [comment]
I am sorry; I didn't get notified of this issue! My apologies for the delay.

See https://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.7.Final/; it's there for sure.
