### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by AssafKatz3** [microbean/microbean-helm#3]
Hi,
Is it possible to add examples to documentation? I saw the tests but it is hard to understand from it.
Thanks,
Assaf

**Comment by ljnelson** [comment]
@AssafKatz3 I am so sorry; I just _now_ noticed this issue!

I work on this project in my spare time, which at the moment is very limited.  I will file an issue to make sure that this does not get lost.  I don't have a time estimate for you.  Thanks for filing the issue!

**Comment by ljnelson** [comment]
Closed with #14.

**Comment by ljnelson** [comment]
(There will be more examples to come, I'm sure, but #14 should address the common ones.)
