### ISSUE TITLE
Need good sample code showing value overrides

### ISSUE THREAD

**Issue by ljnelson** [microbean/microbean-helm#79]
See #78.

**Comment by ljnelson** [comment]
Relevant: https://kubernetes.slack.com/archives/C51E88VDG/p1517254771000026

**Comment by bestro** [comment]
Hi,

I am using the following code in order to install a chart that overrides some values:

		final InstallReleaseRequest.Builder requestBuilder = InstallReleaseRequest.newBuilder();
		requestBuilder.setTimeout(300L);
		requestBuilder.setName("test-charts");
		requestBuilder.setWait(true);

		Map<String, Value> values = new HashMap<>();
		values.put("clusterID", Value.newBuilder().setValue("3").build());
		values.put("initialValue", Value.newBuilder().setValue("4").build());
		requestBuilder.getValuesBuilder().putAllValues(values);

		final Future<InstallReleaseResponse> releaseFuture = releaseManager.install(requestBuilder, chartBuilder);
		final Release release = releaseFuture.get().getRelease();
		
From what I see the values that I send are ignored in **Requirements** class, **Chart.Builder apply(final Chart.Builder chartBuilder, final ConfigOrBuilder userSuppliedValues, final boolean topLevel)** method in case **requirements.yaml** file doesn't exist.

What I want is to generate is the command: "helm install --name test test-charts --set clusterID=3,initialValue=4"

**Comment by ljnelson** [comment]
Hi; thanks for using microBean Helm!

Indeed, microBean Helm does what the `helm` program does: the only way that [values are ever read by Tiller](https://github.com/kubernetes/helm/blob/9654c616c2538530aa8d2388a150eeb31e040851/cmd/helm/install.go#L271) is via the [`setRaw`/`getRaw` methods](https://microbean.github.io/microbean-helm/apidocs/hapi/chart/ConfigOuterClass.Config.Builder.html#setRaw-java.lang.String-).  The format of the `String` that represents the raw values is YAML.

So I would do something like (warning: untested): `requestBuilder.getConfigBuilder().setRaw(myValuesInYAMLFormat)`.

The various values-related methods in the `hapi.*` packages aren't things I have control over (that section of the Java API is generated), but you can see that a `putAllValues` method that takes a `Map` whose values are `Value` objects can't represent an arbitrarily deep YAML tree.  This is a fundamental design flaw in Helm and one that I can't hide or correct.

Thanks again for the issue report!

**Comment by ljnelson** [comment]
You might also be interested in this: https://github.com/microbean/microbean-helm/issues/78#issuecomment-361822333

**Comment by ljnelson** [comment]
Reopening to capture the fact that documentation and examples are still needed.

**Comment by blublinsky** [comment]
Here is the solution that works fine
// cleanup current values
chart.clearValues()
......
// Set the new ones
val requestBuilder = InstallReleaseRequest.newBuilder()
requestBuilder.getValuesBuilder.setRaw(yamlString).build()  // Update values

I am using scala, but it is the same in Java
