### ISSUE TITLE
Loading latest wordpress chart fails with assertion

### ISSUE THREAD

**Issue by avichap** [microbean/microbean-helm#88]
Trying to load the latest fails with assertion on filename.
the wordpress version used locally in tests is 0.6.6 where the latest in the local repository is 0.6.12 
from short investigation the reason seems to be relates to the fact a new template file was added which is not placed directly under '/templates'  rather with additional nesting folder 'tests'

**Comment by ljnelson** [comment]
Investigating.

**Comment by ljnelson** [comment]
Reproduced issue.
