### ISSUE TITLE
Supporting http/s proxy in ChartRepository

### ISSUE THREAD

**Issue by avichap** [microbean/microbean-helm#89]
currently there is no mean for configuring http/s proxy   for the ChartRepository class which have flows which initiate http connection to configured helm repo URLs.

**Comment by ljnelson** [comment]
Addressed.  `fromYaml` now takes a `ChartRepositoryFactory`.  You can thus provide a subclass of `ChartRepository` that overrides its `openStream` method however you like.  For simple proxy issues, setting the right system property is obviously much, much easier.
