### ISSUE TITLE
Tiller 2.8.x support

### ISSUE THREAD

**Issue by frosenberg** [microbean/microbean-helm#90]
Do you have any plans to release support for 2.8.x version of Helm/Tiller? Will the 2.7.2. version be backwards compatible? We have not tried so we cannot tell, but we have been holding off deploying an upgrade to Tiller.

**Comment by ljnelson** [comment]
Hi; yes I do.  I've been holding off since helm 2.8.x seems to be particularly buggy.

As long as the changes stay away from the `requirements.yaml` processing end of things, upgrading should be relatively easy.  I'll look into it in more detail now that I know there's demand.

**Comment by ljnelson** [comment]
Hello, @frosenberg; I've [deployed microbean-helm version 2.8.1.1.0.0-SNAPSHOT to the Sonatype snapshots repository](https://oss.sonatype.org/content/repositories/snapshots/org/microbean/microbean-helm/2.8.1.1.0.0-SNAPSHOT/).  I'd be curious to see what you find.

I've also filed issues for relevant commits that I haven't picked up yet or ported over.  Most of them are trivial but I wanted to make sure I'm capturing everything.  I'll be knocking those off shortly.  Thanks for your interest in microbean-helm.
